"""empty message

Revision ID: 320a6487ad19
Revises: 8e1e69bfef85
Create Date: 2026-01-10 19:41:02.914065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320a6487ad19'
down_revision: Union[str, Sequence[str], None] = '8e1e69bfef85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('age', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demos', 'age')
    # ### end Alembic commands ###
